export const FETCH_BOOKS = 'FETCH_BOOKS';
export const FETCH_BOOKS_BY_ID = 'FETCH_BOOKS_BY_ID';
export const SET_TAGVALUE = 'SET_TAGVALUE';
export const CLEAR_TAGVALUE = 'CLEAR_TAGVALUE';
export const SET_ACTIVETAB = 'SET_ACTIVETAB';
export const CLEAR_TOPTITLE = 'CLEAR_TOPTITLE';
export const SET_TOPTITLE = 'SET_TOPTITLE';